service: resources

frameworkVersion: "3"

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: false
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  environment:
    tableName: ${self:custom.stage}-infrastructure-compose
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:DescribeTable
          # Restrict our IAM role permissions to
          # the specific table for the stage
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.stage}-infrastructure-compose

functions:
  resources:
    handler: src/handler.graphqlHandler
    events:
      - http:
          path: resources
          method: post
