service: billing

frameworkVersion: "3"

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: false

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1

functions:
  billing:
    handler: src/handler.graphqlHandler
    events:
      - http:
          path: billing
          method: post
